import type { AspectRatioInfo, FontInfo, ImageShadow } from './types';

export const ASPECT_RATIOS: AspectRatioInfo[] = [
  {
    name: 'Square (1:1)',
    ratio: '1:1',
    className: 'aspect-square',
  },
  {
    name: 'Story (9:16)',
    ratio: '9:16',
    className: 'aspect-[9/16]',
  },
  {
    name: 'Widescreen (16:9)',
    ratio: '16:9',
    className: 'aspect-[16/9]',
  },
];

export const IMAGE_SHADOW_OPTIONS: { id: ImageShadow, nameKey: string }[] = [
    { id: 'none', nameKey: 'shadowNone' },
    { id: 'sm', nameKey: 'shadowSm' },
    { id: 'md', nameKey: 'shadowMd' },
    { id: 'lg', nameKey: 'shadowLg' },
    { id: 'xl', nameKey: 'shadowXl' },
];


export const FONT_OPTIONS: FontInfo[] = [
  { id: 'archivo-black', name: 'Archivo Black', family: "'Archivo Black', sans-serif" },
  { id: 'arbutus', name: 'Arbutus', family: "'Arbutus', serif" },
  { id: 'atomic-age', name: 'Atomic Age', family: "'Atomic Age', sans-serif" },
  { id: 'audiowide', name: 'Audiowide', family: "'Audiowide', sans-serif" },
  { id: 'bangers', name: 'Bangers', family: "'Bangers', cursive" },
  { id: 'barriecito', name: 'Barriecito', family: "'Barriecito', cursive" },
  { id: 'berkshire-swash', name: 'Berkshire Swash', family: "'Berkshire Swash', cursive" },
  { id: 'caesar-dressing', name: 'Caesar Dressing', family: "'Caesar Dressing', cursive" },
  { id: 'chela-one', name: 'Chela One', family: "'Chela One', cursive" },
  { id: 'chewy', name: 'Chewy', family: "'Chewy', cursive" },
  { id: 'chicle', name: 'Chicle', family: "'Chicle', cursive" },
  { id: 'delius', name: 'Delius', family: "'Delius', cursive" },
  { id: 'delius-unicase', name: 'Delius Unicase', family: "'Delius Unicase', cursive" },
  { id: 'dynapuff', name: 'DynaPuff', family: "'DynaPuff', cursive" },
  { id: 'eagle-lake', name: 'Eagle Lake', family: "'Eagle Lake', cursive" },
  { id: 'erica-one', name: 'Erica One', family: "'Erica One', cursive" },
  { id: 'fascinate', name: 'Fascinate', family: "'Fascinate', cursive" },
  { id: 'finger-paint', name: 'Finger Paint', family: "'Finger Paint', cursive" },
  { id: 'freckle-face', name: 'Freckle Face', family: "'Freckle Face', cursive" },
  { id: 'fruktur', name: 'Fruktur', family: "'Fruktur', cursive" },
  { id: 'germania-one', name: 'Germania One', family: "'Germania One', cursive" },
  { id: 'griffy', name: 'Griffy', family: "'Griffy', cursive" },
  { id: 'hanalei-fill', name: 'Hanalei Fill', family: "'Hanalei Fill', cursive" },
  { id: 'henny-penny', name: 'Henny Penny', family: "'Henny Penny', cursive" },
  { id: 'jaro', name: 'Jaro', family: "'Jaro', sans-serif" },
  { id: 'jolly-lodger', name: 'Jolly Lodger', family: "'Jolly Lodger', cursive" },
  { id: 'joti-one', name: 'Joti One', family: "'Joti One', cursive" },
  { id: 'kablammo', name: 'Kablammo', family: "'Kablammo', cursive" },
  { id: 'knewave', name: 'Knewave', family: "'Knewave', cursive" },
  { id: 'limelight', name: 'Limelight', family: "'Limelight', cursive" },
  { id: 'luckiest-guy', name: 'Luckiest Guy', family: "'Luckiest Guy', cursive" },
  { id: 'metal-mania', name: 'Metal Mania', family: "'Metal Mania', cursive" },
  { id: 'montserrat', name: 'Montserrat', family: "'Montserrat', sans-serif" },
  { id: 'new-rocker', name: 'New Rocker', family: "'New Rocker', cursive" },
  { id: 'nosifer', name: 'Nosifer', family: "'Nosifer', cursive" },
  { id: 'odibee-sans', name: 'Odibee Sans', family: "'Odibee Sans', sans-serif" },
  { id: 'poller-one', name: 'Poller One', family: "'Poller One', cursive" },
  { id: 'poppins', name: 'Poppins', family: "'Poppins', sans-serif" },
  { id: 'protest-guerrilla', name: 'Protest Guerrilla', family: "'Protest Guerrilla', sans-serif" },
  { id: 'righteous', name: 'Righteous', family: "'Righteous', cursive" },
  { id: 'rubik-dirt', name: 'Rubik Dirt', family: "'Rubik Dirt', cursive" },
  { id: 'rubik-distressed', name: 'Rubik Distressed', family: "'Rubik Distressed', cursive" },
  { id: 'rye', name: 'Rye', family: "'Rye', cursive" },
  { id: 'sancreek', name: 'Sancreek', family: "'Sancreek', cursive" },
  { id: 'sigmar', name: 'Sigmar', family: "'Sigmar', cursive" },
  { id: 'skranji', name: 'Skranji', family: "'Skranji', cursive" },
  { id: 'slackey', name: 'Slackey', family: "'Slackey', cursive" },
  { id: 'spicy-rice', name: 'Spicy Rice', family: "'Spicy Rice', cursive" },
  { id: 'titan-one', name: 'Titan One', family: "'Titan One', cursive" },
  { id: 'unlock', name: 'Unlock', family: "'Unlock', cursive" },
  { id: 'vina-sans', name: 'Vina Sans', family: "'Vina Sans', sans-serif" },
  { id: 'wendy-one', name: 'Wendy One', family: "'Wendy One', cursive" },
  { id: 'zen-dots', name: 'Zen Dots', family: "'Zen Dots', sans-serif" },
];
