import type { AspectRatioInfo, FontInfo, ImageShadow } from './types';

export const ASPECT_RATIOS: AspectRatioInfo[] = [
  {
    name: 'Square (1:1)',
    ratio: '1:1',
    className: 'aspect-square',
  },
  {
    name: 'Story (9:16)',
    ratio: '9:16',
    className: 'aspect-[9/16]',
  },
  {
    name: 'Widescreen (16:9)',
    ratio: '16:9',
    className: 'aspect-[16/9]',
  },
];

export const IMAGE_SHADOW_OPTIONS: { id: ImageShadow, nameKey: string }[] = [
    { id: 'none', nameKey: 'shadowNone' },
    { id: 'sm', nameKey: 'shadowSm' },
    { id: 'md', nameKey: 'shadowMd' },
    { id: 'lg', nameKey: 'shadowLg' },
    { id: 'xl', nameKey: 'shadowXl' },
];


export const FONT_OPTIONS: FontInfo[] = [
  { id: 'montserrat', name: 'Montserrat', family: "'Montserrat', sans-serif" },
  { id: 'poppins', name: 'Poppins', family: "'Poppins', sans-serif" },
  { id: 'righteous', name: 'Righteous', family: "'Righteous', cursive" },
  { id: 'barriecito', name: 'Barriecito', family: "'Barriecito', cursive" },
  { id: 'jolly-lodger', name: 'Jolly Lodger', family: "'Jolly Lodger', cursive" },
  { id: 'joti-one', name: 'Joti One', family: "'Joti One', cursive" },
  { id: 'chewy', name: 'Chewy', family: "'Chewy', cursive" },
  { id: 'caesar-dressing', name: 'Caesar Dressing', family: "'Caesar Dressing', cursive" },
  { id: 'new-rocker', name: 'New Rocker', family: "'New Rocker', cursive" },
  { id: 'rye', name: 'Rye', family: "'Rye', cursive" },
  { id: 'sancreek', name: 'Sancreek', family: "'Sancreek', cursive" },
  { id: 'unlock', name: 'Unlock', family: "'Unlock', cursive" },
  { id: 'odibee-sans', name: 'Odibee Sans', family: "'Odibee Sans', sans-serif" },
  { id: 'luckiest-guy', name: 'Luckiest Guy', family: "'Luckiest Guy', cursive" },
  { id: 'protest-guerrilla', name: 'Protest Guerrilla', family: "'Protest Guerrilla', sans-serif" },
  { id: 'nosifer', name: 'Nosifer', family: "'Nosifer', cursive" },
  { id: 'skranji', name: 'Skranji', family: "'Skranji', cursive" },
  { id: 'freckle-face', name: 'Freckle Face', family: "'Freckle Face', cursive" },
  { id: 'dynapuff', name: 'DynaPuff', family: "'DynaPuff', cursive" },
  { id: 'slackey', name: 'Slackey', family: "'Slackey', cursive" },
  { id: 'finger-paint', name: 'Finger Paint', family: "'Finger Paint', cursive" },
  { id: 'delius', name: 'Delius', family: "'Delius', cursive" },
  { id: 'sour-gummy', name: 'Sour Gummy', family: "'Sour Gummy', cursive" },
  { id: 'delius-unicase', name: 'Delius Unicase', family: "'Delius Unicase', cursive" },
  { id: 'henny-penny', name: 'Henny Penny', family: "'Henny Penny', cursive" },
  { id: 'germania-one', name: 'Germania One', family: "'Germania One', cursive" },
  { id: 'spicy-rice', name: 'Spicy Rice', family: "'Spicy Rice', cursive" },
  { id: 'wendy-one', name: 'Wendy One', family: "'Wendy One', cursive" },
  { id: 'chela-one', name: 'Chela One', family: "'Chela One', cursive" },
  { id: 'griffy', name: 'Griffy', family: "'Griffy', cursive" },
  { id: 'berkshire-swash', name: 'Berkshire Swash', family: "'Berkshire Swash', cursive" },
  { id: 'creepster', name: 'Creepster', family: "'Creepster', cursive" },
  { id: 'eater', name: 'Eater', family: "'Eater', cursive" },
  { id: 'mountains-of-christmas', name: 'Mountains of Christmas', family: "'Mountains of Christmas', cursive" },
  { id: 'pangolin', name: 'Pangolin', family: "'Pangolin', cursive" },
  { id: 'patrick-hand-sc', name: 'Patrick Hand SC', family: "'Patrick Hand SC', cursive" },
  { id: 'yusei-magic', name: 'Yusei Magic', family: "'Yusei Magic', sans-serif" },
  { id: 'irish-grover', name: 'Irish Grover', family: "'Irish Grover', cursive" },
  { id: 'original-surfer', name: 'Original Surfer', family: "'Original Surfer', cursive" },
  { id: 'mystery-quest', name: 'Mystery Quest', family: "'Mystery Quest', cursive" },
  { id: 'gorditas', name: 'Gorditas', family: "'Gorditas', cursive" },
  { id: 'frijole', name: 'Frijole', family: "'Frijole', cursive" },
  { id: 'boogaloo', name: 'Boogaloo', family: "'Boogaloo', cursive" },
  { id: 'piedra', name: 'Piedra', family: "'Piedra', cursive" },
  { id: 'chelsea-market', name: 'Chelsea Market', family: "'Chelsea Market', cursive" },
  { id: 'galindo', name: 'Galindo', family: "'Galindo', cursive" },
  { id: 'rubik-vinyl', name: 'Rubik Vinyl', family: "'Rubik Vinyl', cursive" },
  { id: 'passero-one', name: 'Passero One', family: "'Passero One', cursive" },
  { id: 'rubik-scribble', name: 'Rubik Scribble', family: "'Rubik Scribble', cursive" },
  { id: 'road-rage', name: 'Road Rage', family: "'Road Rage', cursive" },
  { id: 'rubik-dirt', name: 'Rubik Dirt', family: "'Rubik Dirt', cursive" },
  { id: 'protest-revolution', name: 'Protest Revolution', family: "'Protest Revolution', sans-serif" },
  { id: 'fredericka-the-great', name: 'Fredericka the Great', family: "'Fredericka the Great', cursive" },
  { id: 'underdog', name: 'Underdog', family: "'Underdog', cursive" },
  { id: 'permanent-marker', name: 'Permanent Marker', family: "'Permanent Marker', cursive" },
  { id: 'averia-libre', name: 'Averia Libre', family: "'Averia Libre', cursive" },
  { id: 'lacquer', name: 'Lacquer', family: "'Lacquer', cursive" },
];
